// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /me/coach-access/{grantId}"
  | "DELETE /me/food-entries/{entryId}"
  | "GET /me/clients"
  | "GET /me/clients/{clientId}/food-entries"
  | "GET /me/clients/{clientId}/goal"
  | "GET /me/clients/{clientId}/progress"
  | "GET /me/coach-access"
  | "GET /me/food-entries"
  | "GET /me/goal"
  | "GET /me/progress"
  | "POST /me/coach-access"
  | "POST /me/food-entries"
  | "PUT /me/food-entries/{entryId}"
  | "PUT /me/goal";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /me/coach-access/{grantId}": { kind: "scope", scope: "coach-access:manage" },
  "DELETE /me/food-entries/{entryId}": { kind: "scope", scope: "food-entries:write" },
  "GET /me/clients": { kind: "scope", scope: "coach-access:read" },
  "GET /me/clients/{clientId}/food-entries": { kind: "scope", scope: "food-entries:read-granted" },
  "GET /me/clients/{clientId}/goal": { kind: "scope", scope: "daily-goal:read-granted" },
  "GET /me/clients/{clientId}/progress": { kind: "scope", scope: "progress:read-granted" },
  "GET /me/coach-access": { kind: "scope", scope: "coach-access:manage" },
  "GET /me/food-entries": { kind: "scope", scope: "food-entries:read" },
  "GET /me/goal": { kind: "scope", scope: "daily-goal:read" },
  "GET /me/progress": { kind: "scope", scope: "progress:read" },
  "POST /me/coach-access": { kind: "scope", scope: "coach-access:manage" },
  "POST /me/food-entries": { kind: "scope", scope: "food-entries:write" },
  "PUT /me/food-entries/{entryId}": { kind: "scope", scope: "food-entries:write" },
  "PUT /me/goal": { kind: "scope", scope: "daily-goal:write" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
