// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "coach-access:manage"
  | "coach-access:read"
  | "daily-goal:read"
  | "daily-goal:read-granted"
  | "daily-goal:write"
  | "food-entries:read"
  | "food-entries:read-granted"
  | "food-entries:write"
  | "progress:read"
  | "progress:read-granted";

export type Role =
  | "Client"
  | "Coach";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["coach-access:manage", "coach-access:read", "daily-goal:read", "daily-goal:read-granted", "daily-goal:write", "food-entries:read", "food-entries:read-granted", "food-entries:write", "progress:read", "progress:read-granted"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Client", "Coach"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Client": ["coach-access:manage", "daily-goal:read", "daily-goal:write", "food-entries:read", "food-entries:write", "progress:read"],
  "Coach": ["coach-access:read", "daily-goal:read-granted", "food-entries:read-granted", "progress:read-granted"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Client": ["Clients"],
  "Coach": ["Coaches"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Client": [],
  "Coach": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
